---
ID: "16e3d218-31c3-20d6-0636-9e476fed8a61"
Parent: "e717094f-2937-28de-3768-1c11704d837b"
Template: "c3b037a0-46e5-4b67-ac7a-a144b962a56f"
Path: /sitecore/layout/Placeholder Settings/Hackathon.RandomPick/Project
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170501T174657Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
