---
ID: "7a4a996c-179d-4295-b7eb-091463473dfe"
Parent: "fb0659d1-fcf0-4f6c-90b4-263a749d778f"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/Hackathon.RandomPick/Feature/PageTour/Assignments/Tasks/Due date
DB: master
SharedFields:
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: Date
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190302T183759Z
