---
ID: "ea2eeb5b-c6ef-4503-a9a6-397bdafcf382"
Parent: "fb0659d1-fcf0-4f6c-90b4-263a749d778f"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/Hackathon.RandomPick/Feature/PageTour/Assignments/Tasks/Person Responsible
DB: master
SharedFields:
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: "Single-Line Text"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 400
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190302T183820Z
